name: Develop Branch CI
on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - 'develop'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: scalecube/spinless
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
      - name: Download Helm
        run: |
          curl -L https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz | tar -xzf - --strip-component=1 linux-amd64/helm
          chmod +x helm
      - name: Package and publish to helm registry
        run: |
          for directory in `find ./charts -type d -maxdepth 1 -mindepth 1`
          do
            echo Helm package for $directory
            name=$(cat $directory/Chart.yaml | grep ^name: | cut -d: -f2 | cut -c 2- | tr -d '"')
            chart_version=$(cat $directory/Chart.yaml | grep ^version: | cut -d: -f2 | cut -c 2- | tr -d '"')
            release_version=$chart_version-${{ env.RELEASE_VERSION }}
            echo Helm chart version $release_version
            # change helm chart version in Chart.yaml
            sed -i.bak 's/version:.*/version: '$release_version'/g' $directory/Chart.yaml
            helm lint --strict $directory || exit 1
            helm template --debug $directory
            helm package --debug $directory
            pkg=$name-$release_version.tgz
            curl -sSf -u ${{ secrets.HELM_REGISTRY_USER }}:${{ secrets.HELM_REGISTRY_PASSWORD }} -X PUT -T $pkg ${{ secrets.HELM_REGISTRY_URL }}/${{ github.repository_owner }}/$name/$pkg
            # revert changes of helm chart version and remove bak files
            rm $directory/Chart.yaml
            mv $directory/Chart.yaml.bak $directory/Chart.yaml
          done