name: Pipeline spinless

on:
  push:
    branches:
      - develop

jobs:

  docker-build-push:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.IMAGE_NAME }}:${GITHUB_REF##*/}

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: push image to registry
      run: |
        docker push ${{ secrets.IMAGE_NAME }}:${GITHUB_REF##*/}

  helm-package-post:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: Install Helm package
      run: |
        wget -q ${{ secrets.HELM_URL }}/${{ secrets.HELM_TGZ }}
        tar xzfv ${{ secrets.HELM_TGZ }}
        PATH=`pwd`/linux-amd64/:$PATH && helm init --client-only

    - name: Check Helm package
      run: |
        cd ./helm
        helm lint ./scalecube-spinless
        helm package ./scalecube-spinless

    - name: POST Helm package
      run: |
        for helm_package in $(find . -name '*.tgz'); do curl -is -u ${{ secrets.HELM_USER}}:${{ secrets.HELM_PASSWORD }} ${{ secrets.HELM_REGISTRY }}/spinless/$helm_package --upload-file $helm_package; done


  robokit-deploy:

    needs:
      - docker-build-push
      - helm-package-post

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          echo 'Robokit Deploy Triggered.'